name: alimentos_taco
description: Api de alimentos da tabela TACO utilizando o framework vaden.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  postgres: ^3.5.4
  vaden: ^0.0.8

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.0.8